#!/usr/bin/env python

"""
Advent of Code 2022, day 2
Will Karnasiewicz
"""

# Input Data

with open("./inputs/will-input.txt") as f:
    input_list = f.read().rstrip("\n").split("\n")

BASE_PTS_1 = {"X": 1, "Y": 2, "Z": 3}
MATCH_PTS_1 = {
    "A X": 3,
    "A Y": 6,
    "A Z": 0,
    "B X": 0,
    "B Y": 3,
    "B Z": 6,
    "C X": 6,
    "C Y": 0,
    "C Z": 3,
}

MATCH_PTS_2 = {"X": 0, "Y": 3, "Z": 6}
PLAY_2 = {    
    "A X": "Z",
    "A Y": "X",
    "A Z": "Y",
    "B X": "X",
    "B Y": "Y",
    "B Z": "Z",
    "C X": "Y",
    "C Y": "Z",
    "C Z": "X",
}

# # Parts 1 and 2


def rps1(inputs):
    score = 0
    for match in inputs:
        score += BASE_PTS_1[match[-1]] + MATCH_PTS_1[match]
    return score


def rps2(inputs):
    score = 0
    for match in inputs:
        score += MATCH_PTS_2[match[-1]] + BASE_PTS_1[PLAY_2[match]]
    return score


if __name__ == "__main__":
    print(f"Part 1: {rps1(input_list)}")
    print(f"Part 2: {rps2(input_list)}")
